### ISSUE TITLE
Pause Monitoring the Queue

### ISSUE THREAD

**Issue by jnovack** [runk/redisq#12]
Let us suppose that the message being pulled out of the queue has failed (and needs to be re-entered into the queue) because one of the prerequisites is not available. In this case, the message will still attempted to be processed on each event loop.

Is there a way to pause reading the queue (from the worker end) so that reactive action (for example) can be taken?  

I do not need the message being removed and readded thousands of times before acting upon the broken prereq.

**Comment by runk** [comment]
It could be closed I think
