### ISSUE TITLE
redisq gracefull shutdown

### ISSUE THREAD

**Issue by mik977** [runk/redisq#14]
A method is missing in the redisq module, that would allow a graceful shutdown if one wants to restart a server (connection to redis is never released).

ex.
redisq.js

module.exports.end = function() {
  redis.client().end();
}

maybe queues should be destroyed as well...

**Comment by mik977** [comment]
You may also consider allowing to pass a redis connection in the options in addition to host/port.

**Comment by runk** [comment]
What do you think if I add a reconnection timer instead?

**Comment by mik977** [comment]
I didn't mean redis server shutdown. I meant when you shutdown your app which uses redisq. 

Node will not shutdown until it has open connections (event listeners) unless you explicitly exit(). It is good practice to remove all event listeners in order to let node exit normally. redisq never releases the redis connection. Another case is when someone uses a node redis wrapper (sentinel failover mode) which allows to work with multiple redis instances. this wrapper has the same api but manages reconnections and other things transparently. 

I think the best would be to have 2 modes. 

1.st mode: let redisq manage redis connection (maybe with reconnections as you proposed)
2.nd mode: let user pass a redis client and let the management to the user passed redis client module

in the 1.st case you also need the above mentioned end() method to detach event listeners from node event queue when a restart or shutdown is needed. In the 2.nd case user manages everything. 

I've seen this practice in another module, RedisStore i think.

This way redisq would be much more flexible.

**Comment by runk** [comment]
`v0.1.17` is out, now you can provide redis client as part on configuration like

``` javascript
var myClient = require('redis').createClient(6379, 'example.com');
redisq.options({redis: myClient});
```

**Comment by runk** [comment]
let me know if you're happy with it

**Comment by mik977** [comment]
Happy ... thank you very much!
