### ISSUE TITLE
Password is visible in ps

### ISSUE THREAD

**Issue by ChrisCinelli** [runk/redisq#3]
$ ps aux | grep node

Produce entries like:

chris          38548   0.0  0.1  3073444  17288 s002  S+    4:27PM   0:00.23 /usr/local/bin/node /Users/chris/offlineWorkers/node_modules/redisq/frontend/cluster {"port":3001,"host":"localhost","opts":{"redis":{"port":6379,"host":"localhost","password":"mypwd"}}}

It would be nicer if the password was not visible.

**Comment by runk** [comment]
Hi there.

I've encountered some difficulties with cluster module, it seems to have trouble with forking children while cluster itself works in a forked process.

Removed cluster for a while, suppose single worker is just enough.

**Comment by ChrisCinelli** [comment]
Are you saying that you can only have one worker now? :-/

**Comment by runk** [comment]
I said that there were N frontend workers, threads, i.e. cluster workers. Now there is only one.

---

You can still have any number of workers that process your tasks :)
