### ISSUE TITLE
Failed Jobs: Don't retry, only log as failed

### ISSUE THREAD

**Issue by Laurens0619** [runk/redisq#5]
When I log a failed job (by done("error",fase)) the task will be added to the queue again. 
This causes that the job will be retried forever.

My desire is to only log the error but don't retry the job.

**Comment by runk** [comment]
Hi there.

You can always set a `retry` flag to false.

```
var queue = redisq.queue("myqueue");
queue.retry = false;
```

**Comment by runk** [comment]
It's better to add a few words about this option to the Readme file.

**Comment by runk** [comment]
#0fc4779
